### ISSUE TITLE
Add Backstage Components for all of our platform apps

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius-kubernetes#393]
We need to add components for all of the apps that we use in our platform. Please add the following components as listed below. You can copy the kube-prometheus-stack one for reference.

https://github.com/ortelius/ortelius-kubernetes/blob/main/catalog-info.yaml

apps
```bash
NAME                      SYNC STATUS   HEALTH STATUS
argo-rollouts             Synced        Healthy
argocd                    Synced        Healthy
backstage                 Synced        Healthy
ingress-nginx             Synced        Healthy
jaeger                    Synced        Healthy
kube-prometheus-stack     Synced        Healthy
loki-stack                Synced        Healthy
opentelemetry-collector   Synced        Healthy
ortelius-docs             Synced        Healthy
ortelius-www              Synced        Healthy
podtatohead-prod          Synced        Healthy
postgresql                Synced        Healthy
```

note: dont worry about SYNC STATUS   HEALTH STATUS and ingress-nginx and kube-prometheus-stack already done

example
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kube-prometheus-stack
  description: Ortelius Grafana Instance
  annotations:
    github.com/project-slug: ortelius/ortelius-docs
    github.com/project-readme-path: README.md
    argocd/app-name: kube-prometheus-stack
    backstage.io/kubernetes-id: kube-prometheus-stack
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
```
