### ISSUE TITLE
Add links to components

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius-kubernetes#404]
Now the links in the Backstage Portal doesn't look good as we don't have any. We will need to add links to the components.

```yaml
links:
    - url: https://github.com/ortelius/ortelius-kubernetes
      title: GitHub
      icon: dashboard
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
      title: Artifact Hub
      icon: dashboard
    - url: https://cert-manager.io/docs/
      title: Project Website
      icon: dashboard
```
